---
- hosts: 127.0.0.1
  connection: local

  tasks:
  - vsphere_guest:
      vcenter_hostname: 10.74.68.16
      username: administrator@vsphere.local
      password: Cisco123!
      validate_certs: False
      guest: "{{guest}}"
      state: absent
      force: yes
